/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-20 08:44:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/serproject/project/MeetMe-Turing-Geeks/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meetme/WEB-INF/lib/spring-webmvc-3.2.3.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1369065858000L));
    _jspx_dependants.put("jar:file:/D:/serproject/project/MeetMe-Turing-Geeks/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meetme/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153406682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1444768369644L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.3.RELEASE.jar", Long.valueOf(1444768366287L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Schedule Events</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\" />\r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/Datepair.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.datepair.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheets/jquery.timepicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheets/bootstrap-datepicker.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheets/mycalendarevent.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheets/fullcalendar.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheets/fullcalendar.min.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar counter = 1;\r\n");
      out.write("\t$('.datePair .time').timepicker({\r\n");
      out.write("\t    'showDuration': true,\r\n");
      out.write("\t    'timeFormat': 'H:i:s'\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('.datePair .date').datepicker({\r\n");
      out.write("\t    'format': 'yyyy-mm-dd',\r\n");
      out.write("\t    'autoclose': true\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tvar datePairval = document.getElementById('datePair');\r\n");
      out.write("    var datepair = new Datepair(datePairval);\r\n");
      out.write("\r\n");
      out.write("     $(\"#addButton\").click(function () {\t\r\n");
      out.write("\t/* if(counter>10){\r\n");
      out.write("            alert(\"Only 10 textboxes allow\");\r\n");
      out.write("            return false;\r\n");
      out.write("\t}\r\n");
      out.write("\t var newDiv = $(document.createElement('div'))\r\n");
      out.write("\t     .attr(\"id\", 'Div' + counter); */\r\n");
      out.write("\tvar newDiv = $('<div id=\"Div'+ counter +'\">');\r\n");
      out.write("    var newDatePair = $(\"<div id='datePair\"+counter+\"'  class='datePair'>\");\r\n");
      out.write("    var input1 = $('<input name=\"startDate'+ counter +'\" id=\"startDate'+ counter +'\" type=\"text\" class=\"date start\"/>');\r\n");
      out.write("    var space1 = $('<span> </span>');\r\n");
      out.write("    var input2 = $('<input name=\"startTime'+ counter +'\" id=\"startTime'+ counter +'\" type=\"text\" class=\"time start ui-timepicker-input\" />');\r\n");
      out.write("    var word = $('<span> to </span>');\r\n");
      out.write("    var input3 = $('<input name=\"endTime'+ counter +'\" id=\"endTime'+ counter +'\" type=\"text\" class=\"time end ui-timepicker-input\" />');\r\n");
      out.write("    var space2 = $('<span> </span>');\r\n");
      out.write("    var input4 = $('<input name=\"endDate'+ counter +'\" id=\"endDate'+ counter +'\" type=\"text\" class=\"date end\"/>');\r\n");
      out.write("    var newLine = $('<br/>');\r\n");
      out.write("\t/* newDiv.after().html('<div id=\"datePair\">');            \r\n");
      out.write("\tnewDiv.after().html('<input class= \"date start\" type=\"text\" id=\"startDate'+ counter +'\" />');\r\n");
      out.write("\tnewDiv.after().html('<input class= \"time start ui-timepicker-input\" type=\"text\" id=\"startTime' + counter + '\" />');\r\n");
      out.write("\tnewDiv.after().html('<input class= \"time end\" type=\"text\" id=\"endTime' + counter + '\" />');\r\n");
      out.write("\tnewDiv.after().html('<input class= \"date end\" type=\"text\" id=\"endDate' + counter + '\" />');\r\n");
      out.write("\tnewDiv.after().html('</div>');  */\r\n");
      out.write("\t$( \"#TextBoxesGroup\" ).append(newDiv);\r\n");
      out.write("\t$(newDiv).append(newDatePair);\r\n");
      out.write("\t$( newDatePair ).append(input1);\r\n");
      out.write("\t$( newDatePair ).append(space1);\r\n");
      out.write("\t$( newDatePair ).append(input2);\r\n");
      out.write("\t$( newDatePair ).append(word);\r\n");
      out.write("\t$( newDatePair ).append(input3);\r\n");
      out.write("\t$( newDatePair ).append(space2);\r\n");
      out.write("\t$( newDatePair ).append(input4);\r\n");
      out.write("\t$( newDatePair ).append(newLine);\r\n");
      out.write("\tvar id = \"datePair\"+counter;\r\n");
      out.write("\t$('.datePair .time').timepicker({\r\n");
      out.write("\t    'showDuration': true,\r\n");
      out.write("\t    'timeFormat': 'H:i:s'\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('.datePair .date').datepicker({\r\n");
      out.write("\t    'format': 'yyyy-mm-dd',\r\n");
      out.write("\t    'autoclose': true\r\n");
      out.write("\t});\r\n");
      out.write("\tvar datePairval = document.getElementsByClassName('datePair');\r\n");
      out.write("\tvar datepair;\r\n");
      out.write("\tfor (var i=0;i<datePairval.length;i+=1){\r\n");
      out.write("\t\tdatepair = new Datepair(datePairval[i]);\r\n");
      out.write("\t}\r\n");
      out.write("//    var datepair = new Datepair(datePairval);\r\n");
      out.write("\r\n");
      out.write("\t/*  newDatePair, input1, input2,input3,input4,newDatePairEnd,newDivEnd ); */\r\n");
      out.write("\t//newDiv.appendTo(\"#TextBoxesGroup\");\r\n");
      out.write("\tcounter++;\r\n");
      out.write("\t$(\"#counter\").val(counter);\r\n");
      out.write("     });\r\n");
      out.write("\r\n");
      out.write("     $(\"#removeButton\").click(function () {\r\n");
      out.write("\tif(counter==1){\r\n");
      out.write("          alert(\"No more event timings to remove\");\r\n");
      out.write("          return false;\r\n");
      out.write("       }   \r\n");
      out.write("        \r\n");
      out.write("\tcounter--;\r\n");
      out.write("\t$(\"#counter\").val(counter);\r\n");
      out.write("\t\t\t\r\n");
      out.write("        $(\"#Div\" + counter).remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("     });\r\n");
      out.write("\t\t\r\n");
      out.write("      $(\"#getButtonValue\").click(function () {\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar msg = '';\r\n");
      out.write("\tfor(i=1; i<counter; i++){\r\n");
      out.write("   \t  msg += \"\\n Event #\" + i + \" : \" + $('#textbox' + i).val();\r\n");
      out.write("\t}\r\n");
      out.write("    \t  alert(msg);\r\n");
      out.write("     });\r\n");
      out.write("     var frm = $('#calendarSubmit');\r\n");
      out.write("     $(\"#submit\").click(function(){\r\n");
      out.write("    \t $.ajax({\r\n");
      out.write("    \t\t type:frm.attr('method'),\r\n");
      out.write("    \t\t url:frm.attr('action'),\r\n");
      out.write("    \t\t data:frm.serialize(),\r\n");
      out.write("    \t\t success: function(data){\r\n");
      out.write("    \t\t\t top.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/success\";\r\n");
      out.write("    \t\t\t alert('Email has been sent with the meeting Invite');\r\n");
      out.write("    \t\t }\r\n");
      out.write("    \t \t /* /* error: function(data){\r\n");
      out.write("    \t \t\t alert('There was an issue sending the information. Please schedule the meeting again.');\r\n");
      out.write("    \t \t\ttop.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/calendar\"; \r\n");
      out.write("    \t \t } */\r\n");
      out.write("    \t });\r\n");
      out.write("     });\r\n");
      out.write("  });\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\"> Meet Me!</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard_landing\">Home</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Contact Us</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Settings</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Profile</a>\r\n");
      out.write("\t\t\t<li><button type=\"button\" class=\"btn btn-success pull-right\" aria-label=\"profile\">\r\n");
      out.write("\t\t\t\t<span class=\"glyphicon  glyphicon-user\" style=\"vertical-align:middle, horizontal-align:right\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-md-2\" style=\" padding-top: 20px;\">\r\n");
      out.write("\t\t<ul class=\"nav nav-pills nav-stacked\" >\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/schedule\">Schedule</a>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/calendar\">Manual Schedule</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\">My Calendar</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Import Calendars</a>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/meetingTime\">Get Meeting Time</a>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<h2>Create your event</h2>\r\n");
      out.write("\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/views/calendar.jsp(172,1) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setId("calendarSubmit");
    // /WEB-INF/views/calendar.jsp(172,1) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "role", "form");
    // /WEB-INF/views/calendar.jsp(172,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("POST");
    // /WEB-INF/views/calendar.jsp(172,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction("/meetme/manualCalendar");
    // /WEB-INF/views/calendar.jsp(172,1) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setCommandName("calendar");
    // /WEB-INF/views/calendar.jsp(172,1) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div class=\"form-group\" style=\" margin-left: 0px; width: 800px; height: 65px; padding-top: 7px;margin-bottom: 0px;\">\r\n");
          out.write("\t\t<label class=\"control-label col-sm-2\" for=\"event-name\" style=\"text-align: center;\">Event Name:</label>\r\n");
          out.write("\t\t\t<div class=\"col-sm-4\" style=\"padding-left: 75px; padding-right: 0px; width: 395px;\">\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t<div class=\"form-group\" style=\"width: 1000px;margin-bottom: 0px;\">\r\n");
          out.write("\t\t<label class=\"control-label col-sm-2\" for=\"event-description\">Event Description:</label>\r\n");
          out.write("\t\t\t<div class=\"col-sm-4\" style=\"width: 380px; padding-left: 40px;\">\t\t\t\t\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_form_005ftextarea_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t<div class=\"row\" style=\"padding-top: 25px; padding-bottom: 25px;\">\r\n");
          out.write("\t\t<label class=\"control-label col-sm-2\" for=\"event-name\" style=\"width: 340px;padding-left: 50px;\">Probable Date and Time:</label>\r\n");
          out.write("\t\t\t<div class=\"col-md-8\" style=\"padding-left: 0px;\">\r\n");
          out.write("\t\t\t\t<div id='TextBoxesGroup'>\r\n");
          out.write("\t\t\t\t\t<div id=\"Div0\">\r\n");
          out.write("\t\t\t\t\t\t<div id=\"datePair\" class=\"datePair\">\r\n");
          out.write("\t\t\t\t\t\t\t<input name=\"startDate0\" id=\"startDate0\" type=\"text\" class=\"date start\" />\r\n");
          out.write("\t\t\t\t\t\t\t<input name=\"startTime0\" id=\"startTime0\" type=\"text\" class=\"time start ui-timepicker-input\"  /> to\r\n");
          out.write("\t\t\t\t\t\t\t<input name=\"endTime0\" id=\"endTime0\" type=\"text\" class=\"time end ui-timepicker-input\" />\r\n");
          out.write("\t\t\t\t\t\t\t<input name=\"endDate0\" id=\"endDate0\" type=\"text\" class=\"date end\"/>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<input name=\"counter\" type=\"hidden\" id=\"counter\" value=\"1\" />\r\n");
          out.write("\t\t\t\t</div> \r\n");
          out.write("\t\t\t</div>\t\t\t\t\t\r\n");
          out.write("\t\t\t<div class=\"col-md-1\" style=\"padding-top: 10px;\">\r\n");
          out.write("\t    \t\t<input type='button' value='Add More' id='addButton' class=\"btn btn-success\">\r\n");
          out.write("\t    \t</div>\r\n");
          out.write("\t    \t<div class=\"col-md-1\" style=\"padding-top: 10px;\"> \r\n");
          out.write("\t\t\t\t<input type='button' value='Remove' id='removeButton' class=\"btn btn-danger\">\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t<div class=\"form-group\">\r\n");
          out.write("\t\t<label class=\"control-label col-sm-2\" for=\"event-name\" style=\"width: 290px;\">Required People: </label>\r\n");
          out.write("\t\t\t<div class=\"col-sm-4\" style=\" width: 393px; padding-left: 48px;\">\t\t\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_form_005ftextarea_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t<div class=\"form-group\">\r\n");
          out.write("\t\t<label class=\"control-label col-sm-2\" for=\"event-name\" style=\"width: 290px;\">Optional People: </label>\r\n");
          out.write("\t\t\t<div class=\"col-sm-4\" style=\" width: 393px; padding-left: 48px;\">\t\t\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_form_005ftextarea_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t\t<button type=\"button\" id=\"submit\" class=\"btn btn-success\">Done!</button> \r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/calendar.jsp(176,4) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "type", "text");
    // /WEB-INF/views/calendar.jsp(176,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("eventName");
    // /WEB-INF/views/calendar.jsp(176,4) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "placeholder", "Enter Event Name");
    // /WEB-INF/views/calendar.jsp(176,4) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005ftextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:textarea
    org.springframework.web.servlet.tags.form.TextareaTag _jspx_th_form_005ftextarea_005f0 = (org.springframework.web.servlet.tags.form.TextareaTag) _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.TextareaTag.class);
    _jspx_th_form_005ftextarea_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005ftextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/calendar.jsp(182,4) name = rows type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f0.setRows("3");
    // /WEB-INF/views/calendar.jsp(182,4) name = cols type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f0.setCols("50");
    // /WEB-INF/views/calendar.jsp(182,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f0.setPath("eventDescription");
    // /WEB-INF/views/calendar.jsp(182,4) null
    _jspx_th_form_005ftextarea_005f0.setDynamicAttribute(null, "placeholder", "Give Event Description");
    // /WEB-INF/views/calendar.jsp(182,4) null
    _jspx_th_form_005ftextarea_005f0.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_form_005ftextarea_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005ftextarea_005f0 = _jspx_th_form_005ftextarea_005f0.doStartTag();
      if (_jspx_th_form_005ftextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005ftextarea_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005ftextarea_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005ftextarea_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody.reuse(_jspx_th_form_005ftextarea_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005ftextarea_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:textarea
    org.springframework.web.servlet.tags.form.TextareaTag _jspx_th_form_005ftextarea_005f1 = (org.springframework.web.servlet.tags.form.TextareaTag) _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.TextareaTag.class);
    _jspx_th_form_005ftextarea_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005ftextarea_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/calendar.jsp(210,4) name = rows type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f1.setRows("3");
    // /WEB-INF/views/calendar.jsp(210,4) name = cols type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f1.setCols("50");
    // /WEB-INF/views/calendar.jsp(210,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f1.setPath("guestRequiredEmail");
    // /WEB-INF/views/calendar.jsp(210,4) null
    _jspx_th_form_005ftextarea_005f1.setDynamicAttribute(null, "placeholder", "Enter Email ID's of people who are required to attend the meeting");
    // /WEB-INF/views/calendar.jsp(210,4) null
    _jspx_th_form_005ftextarea_005f1.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_form_005ftextarea_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005ftextarea_005f1 = _jspx_th_form_005ftextarea_005f1.doStartTag();
      if (_jspx_th_form_005ftextarea_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005ftextarea_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005ftextarea_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005ftextarea_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody.reuse(_jspx_th_form_005ftextarea_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005ftextarea_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:textarea
    org.springframework.web.servlet.tags.form.TextareaTag _jspx_th_form_005ftextarea_005f2 = (org.springframework.web.servlet.tags.form.TextareaTag) _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.TextareaTag.class);
    _jspx_th_form_005ftextarea_005f2.setPageContext(_jspx_page_context);
    _jspx_th_form_005ftextarea_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/calendar.jsp(216,4) name = rows type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f2.setRows("3");
    // /WEB-INF/views/calendar.jsp(216,4) name = cols type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f2.setCols("50");
    // /WEB-INF/views/calendar.jsp(216,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f2.setPath("guestOptionalEmail");
    // /WEB-INF/views/calendar.jsp(216,4) null
    _jspx_th_form_005ftextarea_005f2.setDynamicAttribute(null, "placeholder", "Enter Email ID's of people who are optional for the meeting");
    // /WEB-INF/views/calendar.jsp(216,4) null
    _jspx_th_form_005ftextarea_005f2.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_form_005ftextarea_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_form_005ftextarea_005f2 = _jspx_th_form_005ftextarea_005f2.doStartTag();
      if (_jspx_th_form_005ftextarea_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005ftextarea_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005ftextarea_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005ftextarea_005f2.doFinally();
      _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fcols_005fclass_005fnobody.reuse(_jspx_th_form_005ftextarea_005f2);
    }
    return false;
  }
}
