/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-21 08:26:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class success_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/serproject/project/MeetMe-Turing-Geeks/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meetme/WEB-INF/lib/spring-webmvc-3.2.3.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1369065858000L));
    _jspx_dependants.put("jar:file:/D:/serproject/project/MeetMe-Turing-Geeks/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meetme/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153406682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1444768369644L));
    _jspx_dependants.put("jar:file:/D:/serproject/project/MeetMe-Turing-Geeks/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/meetme/WEB-INF/lib/spring-webmvc-3.2.3.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1369065858000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.3.RELEASE.jar", Long.valueOf(1444768366287L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fid_005fcols_005fclass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fid_005fcols_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fid_005fcols_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title> Dashboard</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width,default-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/ui/1.11.3/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script> -->\r\n");
      out.write("\t<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/moment.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/fullcalendar.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/fullcalendar.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheets/fullcalendar.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/stylesheets/fullcalendar.min.css\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t  var date = new Date();\r\n");
      out.write("\t\t  var d = date.getDate();\r\n");
      out.write("\t\t  var m = date.getMonth();\r\n");
      out.write("\t\t  var y = date.getFullYear();\r\n");
      out.write("\t\t  alert(\"am here\");\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  $('#calendar').fullCalendar({\r\n");
      out.write("\t\t\theader: {\r\n");
      out.write("\t\t\t  left: 'prev,next today',\r\n");
      out.write("\t\t\t  center: 'title',\r\n");
      out.write("\t\t\t  right: 'month,agendaWeek,agendaDay'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t events: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/calendarFetch',\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t/* eventSources: [\r\n");
      out.write("\r\n");
      out.write("\t\t\t               // your event source\r\n");
      out.write("\t\t\t               {\r\n");
      out.write("\t\t\t                   url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/calendarFetch', // use the `url` property\r\n");
      out.write("\t\t\t                   color: 'yellow',    // an option!\r\n");
      out.write("\t\t\t                   textColor: 'black'  // an option!\r\n");
      out.write("\t\t\t               }\r\n");
      out.write("\r\n");
      out.write("\t\t\t               // any other sources...\r\n");
      out.write("\r\n");
      out.write("\t\t\t           ], */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("/* \t\t\tevents: function(start, end, timezone, callback) {\r\n");
      out.write("\t\t        $.ajax({\r\n");
      out.write("\t\t      url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/calendarFetch',\r\n");
      out.write("\t\t            dataType: \"json\",\r\n");
      out.write("\r\n");
      out.write("\t\t            data: {\r\n");
      out.write("\t\t                start: start.unix(),\r\n");
      out.write("\t\t                end: end.unix()\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            success: function(doc) {\r\n");
      out.write("\t\t            \talert(\"data111\");\r\n");
      out.write("\t\t                var events = [];\r\n");
      out.write("\t\t                $(doc).find('event').each(function() {\r\n");
      out.write("\t\t                \talert(\"data1112222\");\r\n");
      out.write("\t\t                    events.push({\r\n");
      out.write("\t\t                    \t\r\n");
      out.write("\t\t                        title: $(this).attr('title'),\r\n");
      out.write("\t\t                        start: $(this).attr('start') // will be parsed\r\n");
      out.write("\t\t                    });\r\n");
      out.write("\t\t                });\r\n");
      out.write("\t\t                callback(events);\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        });\r\n");
      out.write("\t\t    } */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    \r\n");
      out.write("\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\tselectable: true,\r\n");
      out.write("\t\t\tselectHelper: true,\r\n");
      out.write("\t\t\tselect: function(start, end, allDay) {\r\n");
      out.write("\t\t\t\t$('#eventModal').modal('show'); // popping my modal to create event\r\n");
      out.write("\t\t\t\t$(\"#modal-body\").load('calendar.jsp'); //load up modal-body content\r\n");
      out.write("\r\n");
      out.write("\t\t\t    $(\"#submit\").bind(\"click\", function(event){ // when you click in a create button inside dialog you should send as parameters start,end,etc\r\n");
      out.write("\t\t\t    \t$event_name = $(\"#event_name\").val();\r\n");
      out.write("\t\t\t    \t$event_description = $(\"#event_description\").val();\r\n");
      out.write("\t\t\t    \tvar moment1 = $('#calendar').fullCalendar('getDate');\r\n");
      out.write("\t\t\t        alert(\"The current date of the calendar is \" + moment1.format());\r\n");
      out.write("\t\t\t    \t/* $start_date = $(\"#startDate0\").val();\r\n");
      out.write("\t\t\t    \t$start_time = $(\"#startTime0\").val();\r\n");
      out.write("\t\t\t    \t$end_date = $(\"#endDate0\").val();\r\n");
      out.write("\t\t\t    \t$end_time = $(\"#endTime0\").val();\r\n");
      out.write("\t\t\t    \t$mailing_list = $(\"#mailing_list\").val(); */\r\n");
      out.write("\r\n");
      out.write("\t\t\t            if ($event_name) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t            /* \t$('#calendar').fullCalendar('renderEvent',\r\n");
      out.write("\t\t\t                {\r\n");
      out.write("\t\t\t                    //id: $id, \r\n");
      out.write("\t\t\t                    title: $event_name,\r\n");
      out.write("\t\t\t                    /* start: $start_time,\r\n");
      out.write("\t\t\t                    end: $end_time,\r\n");
      out.write("\t\t\t                    allDay: allDay\r\n");
      out.write("\t\t\t                    /* url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard_landing\" //look at this code with extra care \r\n");
      out.write("\t\t\t                },true); */\r\n");
      out.write("\t\t\t                \r\n");
      out.write("\t\t\t                var myCalendar = $('#calendar'); \r\n");
      out.write("\t\t\t                myCalendar.fullCalendar();\r\n");
      out.write("\t\t\t                var myEvent = {\r\n");
      out.write("\t\t\t                  title:$event_name,\r\n");
      out.write("\t\t\t                  allDay: true,\r\n");
      out.write("\t\t\t                  start: moment1.format(),\r\n");
      out.write("\t\t\t                  end: moment1.format()\r\n");
      out.write("\t\t\t                };\r\n");
      out.write("\t\t\t                myCalendar.fullCalendar( 'renderEvent', myEvent, true );\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t            }else{\r\n");
      out.write("\t\t\t            \t$('#calendar').fullCalendar('unselect');\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t        $('#eventModal').modal('toggle');// close my dialog\r\n");
      out.write("\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teditable: true,\r\n");
      out.write("\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t});\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"> Meet Me!</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"#\">Home</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Contact Us</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Settings</a>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Profile</a>\r\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"btn btn-success pull-right\" aria-label=\"profile\">\r\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon  glyphicon-user\" style=\"vertical-align:middle, horizontal-align:right\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-md-2\" style=\" padding-top: 20px;\">\r\n");
      out.write("\t\t<ul class=\"nav nav-pills nav-stacked\" >\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"#\">Schedule</a>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/calendar\">Manual Schedule</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\">My Calendar</a>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Import Calendars</a>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/meetingTime\">Get Meeting Time</a>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"eventModal\" class=\"modal\" role=\"dialog\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-lg\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t<h4>Create your event</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write(" \t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\" style=\"padding-left: 120px;padding-top: 0px;\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<div id=\"calendar\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005fform_005f0.setParent(null);
    // /WEB-INF/views/success.jsp(192,5) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setId("calendarSubmit");
    // /WEB-INF/views/success.jsp(192,5) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "role", "form");
    // /WEB-INF/views/success.jsp(192,5) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setMethod("POST");
    // /WEB-INF/views/success.jsp(192,5) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setAction("/meetme/calendarEvent");
    // /WEB-INF/views/success.jsp(192,5) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005fform_005f0.setCommandName("calendarInfo");
    // /WEB-INF/views/success.jsp(192,5) null
    _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
    int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
      if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t<div class=\"form-group\">\r\n");
          out.write("\t\t<label class=\"control-label col-sm-2\" for=\"event-name\">Event Name:</label>\r\n");
          out.write("\t\t\t<div class=\"col-sm-10\">\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\r\n");
          out.write("\t<div class=\"form-group\">\r\n");
          out.write("\t\t<label class=\"control-label col-sm-2\"  for=\"event-name\">Event Description:</label>\r\n");
          out.write("\t\t\t<div class=\"col-sm-10\">\t\t\t\t\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_form_005ftextarea_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t</div>\t\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t\t<input type=\"Button\" value=\"Done!\" id=\"submit\" class=\"btn btn-success col-sm-12\"> \r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005fform_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005fform_0026_005frole_005fmethod_005fid_005fcommandName_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/success.jsp(196,4) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "type", "text");
    // /WEB-INF/views/success.jsp(196,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("eventName");
    // /WEB-INF/views/success.jsp(196,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setId("event_name");
    // /WEB-INF/views/success.jsp(196,4) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "placeholder", "Enter Event Name");
    // /WEB-INF/views/success.jsp(196,4) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005fplaceholder_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005ftextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:textarea
    org.springframework.web.servlet.tags.form.TextareaTag _jspx_th_form_005ftextarea_005f0 = (org.springframework.web.servlet.tags.form.TextareaTag) _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fid_005fcols_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.TextareaTag.class);
    _jspx_th_form_005ftextarea_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005ftextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /WEB-INF/views/success.jsp(203,4) name = rows type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f0.setRows("4");
    // /WEB-INF/views/success.jsp(203,4) name = cols type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f0.setCols("50");
    // /WEB-INF/views/success.jsp(203,4) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f0.setId("event_description");
    // /WEB-INF/views/success.jsp(203,4) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005ftextarea_005f0.setPath("eventDescription");
    // /WEB-INF/views/success.jsp(203,4) null
    _jspx_th_form_005ftextarea_005f0.setDynamicAttribute(null, "placeholder", "Give Event Description");
    // /WEB-INF/views/success.jsp(203,4) null
    _jspx_th_form_005ftextarea_005f0.setDynamicAttribute(null, "class", "form-control");
    int[] _jspx_push_body_count_form_005ftextarea_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005ftextarea_005f0 = _jspx_th_form_005ftextarea_005f0.doStartTag();
      if (_jspx_th_form_005ftextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005ftextarea_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005ftextarea_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005ftextarea_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005ftextarea_0026_005frows_005fplaceholder_005fpath_005fid_005fcols_005fclass_005fnobody.reuse(_jspx_th_form_005ftextarea_005f0);
    }
    return false;
  }
}
